var datasets_from_ids = {
    0: '00 -station-meteo-toulouse-valade ',
    2: '02 -station-meteo-toulouse-marengo ',
    3: '03 -station-meteo-toulouse-busca ',
    4: '04 -station-meteo-toulouse-ile-empalot ',
    5: '05 -station-meteo-toulouse-piscine-nakache ',
    7: '07 -station-meteo-toulouse-avenue-de-grande-bretagne ',
    10: '10 -station-meteo-toulouse-castelginest ',
    11: '11 -station-meteo-toulouse-soupetard ',
    12: '12 -station-meteo-toulouse-montaudran ',
    14: '14 -station-meteo-toulouse-center-pierre-potier ',
    15: '15 -station-meteo-toulouse-union ',
    24: '24 -station-meteo-toulouse-colomiers-zi-enjacca ',
    25: '25 -station-meteo-toulouse-tournfeuille ',
    27: '27 -station-meteo-toulouse-saint-cyprien ',
    28: '28 -station-meteo-toulouse-carmes',
    36: '36 -station-meteo-toulouse-purpan ',
    37: '37 -station-meteo-toulouse-universite-paul-sabatier ',
    42: '42 -station-meteo-toulouse-parc-compans-cafarelli ',
    49: '49 -station-meteo-toulouse-cote-pavee ',
    53: '53 -station-meteo-toulouse-ponsan ',
    61: '61 -station-meteo-toulouse-blagnac-center ',
    62: '62 -station-meteo-toulouse-parc-maourine ',
};
